# Site
repository: BenjaminSaintCyr/BenjaminSaintCyr.github.io
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Benjamin Saint-Cyr
title: Student
email: benjamin.saintcyr@gmail.com
website: https://benjaminsaintcyr.github.io/

# Dark Mode (true/false/never)
darkmode: false

# Social links
github_username:  BenjaminSaintCyr
# stackoverflow_username: "00000001"
# facebook_username: jekyll
linkedin_username:  benjamin-saint-cyr-a7464517b
# youtube_username: globalmtb

# Additional icon links
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Benjamin and I'm a junior full stack developer.  I have worked at a number of companies gaining teamwork and leadership skills.

  I am most skilled in: <mark>AWS</mark> and <mark>Eating Pizza</mark>

content:
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: École Polytechnique Montréal
        caption: 2018 - 2022
        sub_title: Bachelor's degree In software Engineering (B.Sc.)
        description: | # this will include new lines to allow paragraphs
           -   GPA : 3,6/4

               Relevant coursework:


           -   INF3710: Files and Databases (**SQL**)

           -   LOG2990: Web application project

               -   Front end with **Angular, SASS, HTML, CSS, TypeScript, JavaScript**
        
               -   Back end with **Express** and **MongoDB**
        
               -   Quality Control with **Gitlab CI** and **Jasmine** (**Unit tests**)

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Morneau Shepell
        link: https://www.morneaushepell.com/
        sub_title: .Net and Angular Junior FullStack developer
        caption: May 2020 - August 2020
        description: | # this will include new lines to allow paragraphs
            -   Web development on a web App with **Angular**
            -   **C\#** and **.Net** development on a Windows server
                -   Make a secure API using **ASP.NET**
            -   Create **SQL** database using **Microsoft SQL Server**
                -   Create **relational** and **graph** database



      - layout: left
        title: DORSAL LAB
        link: https://www.dorsal.polymtl.ca/en
        sub_title: Junior Fullstack Java and React developer
        caption: May 2019 - August 2019
        description: | # this will include new lines to allow paragraphs
            -   Web development on a web App (Theia trace extension) with React and **TypeScript (JavaScript)**
                -   Worked with **Docker**
            - **Java** development on a large **Open Source** project ([Trace Compass](https://www.eclipse.org/tracecompass/)) (Analyze **Linux** **Traces**)
                -   **Unit tests** with **JUnit**
                -   Built an **API** to script and automatize TraceCompass
            -   Version control with **Git**, **Jenkins**, Gerrit and **GitHub**
            -   **Linux** development with **bash/shell**


  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Élikos Society
        link: https://elikos.ca/
        caption: 2018 - 2020
        # link_text: Project Website
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        description: | # this will include new lines to allow paragraphs
          -   Technical director for the structure team

              -   Used Agile methods for project development

          -   Worked with big **C++** and **Python** frameworks like ROS to build the system control of a drone and a mechanical arm


  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
      - fencing
      - baduk
      - emacs

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
